import Head from "next/head";
import Link from "next/link";
import { useEffect } from "react";
import { useRouter } from "next/router";
import { useSignIn } from "../apollo/action";

import { LoginFrom } from "../components";
const Login = () => {
  const router = useRouter();
  const [signIn, { data, loading, error }] = useSignIn();
  const errorMessage = (error) => {
    return (
      (error.graphQLErrors &&
        error.graphQLErrors[0].message &&
        error.message) ||
      "Ooooops something went wrong..."
    );
  };
  useEffect(() => {
    if (data) {
      if (data.signIn.role === "admin") {
        router.push("/admin");
      } else if (data.signIn.role === "employee") {
        router.push("/user");
      } else if (data.signIn.role === "guests") {
        router.push("/");
      }
    }
  }, [data]);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center justify-center h-screen bg-login-page bg-cover bg-no-repeat overflow-y-hidden">
        <div className="max-w-md w-full space-y-8 bg-white px-2 rounded-md">
          <h2 className="mt-6 text-center text-3xl font-extrabold">
            System Hotel Management
          </h2>
          <h2 className="mt-2 text-center text-2xl font-bold">Login</h2>
          <LoginFrom
            loading={loading}
            onSubmit={(signInData) => signIn({ variables: signInData })}
          />
          {error && (
            <div
              className="bg-red-100 rounded-lg py-5 px-6 mb-4 text-base text-red-700 "
              role="alert"
            >
              {errorMessage(error)}
            </div>
          )}
          <div className="flex pb-2 items-center justify-center">
            <Link href="/">
              <a className=" text-blue-700 hover:underline text-sm cursor-pointer">
                lupa password
              </a>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
};

export default Login;
